name: Run main.py regularly√í

on:
#  schedule:
#    - cron: "*/30 * * * *"   # Every 30 minutes (UTC)
  workflow_dispatch:       # allow manual run

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: MY_FIRST_SECRET  # Reference the environment name
    steps:
      - name: Show system info
        run: |
          echo "OS: $(uname -a)"
          echo "CPU: $(nproc) cores"
          echo "Memory: $(free -h | grep Mem)"
          echo "Disk: $(df -h / | tail -1)"
          echo "Runner: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        run: uv sync

      - name: Run main.py
        run: uv run python main.py
        env:
          MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
      
      - name: Run investment_agent/infrastructure/cli/app.py
        run:  uv run python -m invesetment_agent.infrastructure.cli.app
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
