name: Run main.py Every Minute

on:
  schedule:
    - cron: "* * * * *"   # Every minute (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use existing virtual environment
        run: |
          source .venv/bin/activate
          python main.py
